### ISSUE TITLE
verifyCouponOr doesn't return exceptions

### ISSUE THREAD

**Issue by syamsoul** [michael-rubel/laravel-couponables#18]
Hi,

I try this code 

```
$user->verifyCouponOr("ABC123", function($exception){
    dump($exception);
});
```

I expected the output will be the exception (e.g ` MichaelRubel\Couponables\Exceptions\OverQuantityException  The coupon is exhausted.`)

.

but instead, it return the coupon code:

```
"ABC123"
```

.

**Comment by michael-rubel** [comment]
@syamsoul should be fixed in [7.0.4](https://github.com/michael-rubel/laravel-couponables/releases/tag/7.0.4).

Thanks for reporting!
