### ISSUE TITLE
Unknown column 'couponables.couponable_id'

### ISSUE THREAD

**Issue by alvins-dev** [michael-rubel/laravel-couponables#28]
I encountered error with this line.
```
$course->coupons()->get();
```
> Column not found: 1054 Unknown column 'couponables.couponable_id' in 'field list'

Simple solution would be to rename column name in `couponables` table.
Rename the morph field `couponables` to `couponable` ?

**Comment by michael-rubel** [comment]
@alvins-dev It seems you changed the column name after running migrations. Take a look at [this line](https://github.com/michael-rubel/laravel-couponables/blob/main/database/migrations/create_couponables_table.php.stub#L24).

**Comment by alvins-dev** [comment]
Haha. You are absolutory right. Silly me 😅
Thanks for this amazing package!

**Comment by alvins-dev** [comment]
Haha. You are absolutory right. Silly me 😅
Thanks for this amazing package!
