### ISSUE TITLE
Dose not check the owner of the coupon

### ISSUE THREAD

**Issue by stanley-hypo** [michael-rubel/laravel-couponables#5]
I assigned the coupon to $redeemer by saving

redeemer_type=members
redeemer_id=46 (in this case)

I try to use another member to verifyCoupon the coupon and it returns true

$member = Member::find(47);
$coupon = $member->verifyCoupon($code);  << it return no exception

**Comment by stanley-hypo** [comment]
/**
     * Check if the model is allowed to redeem.
     *
     * @param  Model  $redeemer
     *
     * @return bool
     */
    public function isAllowedToRedeemBy(Model $redeemer): bool
    {
        return with(self::$bindable, function ($coupon) use ($redeemer) {
            if ($coupon->isMorphColumnsFilled() && ! $coupon->redeemer()?->is($redeemer)) {
                return false;
            }

            if ($coupon->isOnlyRedeemerTypeFilled() && ! $coupon->isSameRedeemerModel($redeemer)) {
                return false;
            }

            return true;
        });
    }


I found that this function may have some bugs. $coupon is null

**Comment by michael-rubel** [comment]
@stanley-hypo did you override the constructor in your own model?

**Comment by stanley-hypo** [comment]
thanks
